# Site settings
title: "Finn's Tech Blog"
description: "개발자의 성장 기록, 기술 탐구, 그리고 일상의 인사이트"
baseurl: ""
url: "https://bishoe01.github.io"
author: "Finn"
email: "your-email@example.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
timezone: Asia/Seoul
lang: ko

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 6
paginate_path: "/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Finn"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Social links
github_username: bishoe01
# linkedin_username: your_linkedin
# twitter_username: your_twitter

# SEO settings
google_analytics: # Add your tracking ID here
google_site_verification: # Add your verification code here

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
